development:
  amazon_bucket_name: slots-dev
  amazon_access_key: AKIAJVII7JL457FNV7VQ
  amazon_access_secret: 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

production:
  amazon_bucket_name: slots-vegas
  amazon_access_key: AKIAJVII7JL457FNV7VQ
  amazon_access_secret: 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

beta:
  amazon_bucket_name: slots-beta
  amazon_access_key: AKIAJVII7JL457FNV7VQ
  amazon_access_secret: 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
