common: &default_settings
  :access_key_id: <%= API_CONFIG['amazon_access_key'] %>
  :secret_access_key: <%= API_CONFIG['amazon_access_secret'] %>
  :bucket: <%= API_CONFIG['amazon_bucket_name'] %>

production: &production
  :images:
    :file:
      :storage: !ruby/symbol s3
      :s3_protocol: :https
      :s3_credentials:
        <<: *default_settings
      :s3_permissions:
        :original: :public_read
        :mini: :public_read
      :default_url: '/assets/missing.png'
      :styles:
        :mini: '48x48>'
      :url: ":s3_domain_url"
      :path: '/images/:resource_type/:id-:style.:extension'
      :convert_options:
        :all: '-strip -auto-orient -colorspace sRGB'

  :assets:
    :file:
      :storage: !ruby/symbol s3
      :s3_protocol: :https
      :s3_credentials:
        <<: *default_settings
      :s3_permissions:
        :original: :public_read
      :default_url: '/assets/missing.png'
      :url: ":s3_domain_url"
      :path: '/assets/:resource_type/:filename'

development:
  <<: *production

test:
  <<: *production
 
beta:
  <<: *production
